---
apiVersion: v1
kind: Service
metadata:
  name: datascience
  namespace: covid-dash
spec:
  externalName: datascience.capetown.gov.za
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: covid-dash
  namespace: covid-dash
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-regex: ^https?://ds3.capetown.gov.za/covid-dash/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://datascience.capetown.gov.za/vulnerability-viewer/ct-vulnerability-viewer.html
spec:
  rules:
    - host:
      http:
        paths:
          - path: /covid-dash
            backend:
              serviceName: datascience
              servicePort: https